apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: 058264243522.dkr.ecr.ap-northeast-2.amazonaws.com/cats
    newTag: abcdefg
  - name: 058264243522.dkr.ecr.ap-northeast-2.amazonaws.com/dogs
    newTag: abcdefg
  - name: 058264243522.dkr.ecr.ap-northeast-2.amazonaws.com/web
    newTag: abcdefg
